### PR TITLE
Ethereum Block path parsing

### PR DESCRIPTION
**Pull request by kumavis**
This was an interesting exercise and raised some questions.
- how should `resolve` return external links?
- can `resolve` return buffers?
- should `tree` return the values or just the path names?
- since `tree` also returns paths to local data, do we need an api for getting all external links? ( i think yes )
- what is `js-ipld-dag-cbor/src/dag-node`?
- how should we error on path-not-found?
- please add me as a contributor to https://github.com/ipld/js-ipld-eth-block

### CODE REVIEW

**Comment by daviddias** [comment]
Awesome! Answering your questions:

> how should resolve return external links?

Using the IPLD link notation, which is:

`{ '/': <CID> }`

> can resolve return buffers?

Yes

> should tree return the values or just the path names?

both, it returns an array of arrays with full path and value

> since tree also returns paths to local data, do we need an api for getting all external links? ( i think yes )

No, that was one of the constraints that needed to be imposed. a .tree on a block can only yield the values present in that block, a local resolver will never have access to the network. The main resolver (IPLDResolver) will have a higher level .tree

> what is js-ipld-dag-cbor/src/dag-node?

Leftovers, just deleted it.

> how should we error on path-not-found?

Right now, I'm throwing, but not super confident on what is the best API there. It would be sweet to have a bunch of use cases and tests to try out how does that feel as a user.

> please add me as a contributor to https://github.com/ipld/js-ipld-eth-block

I did during the call, you have to accept the invite, should I invite again?

image

**Comment by kumavis** [comment]
Correctly generating IPLD links is blocked by:
- [ ] https://github.com/multiformats/multihash/issues/54
- [ ] https://github.com/multiformats/js-multihash/issues/20

**Comment by jbenet** [comment]
Hold up, I think `tree` should ONLY return the partial (local) paths. Think of it like `find .` in unix, or `tree` in more recent systems. Otherwise this is a very expensive call.

@diasdavid If you want both, then this is turning more into a `Walk` function or iterator (that traverses the graph, returning both path and value per node). This can be an "extended" api, but probably not the base minimum? Let's align on this asap

**Comment by kumavis** [comment]
oops merged this into master accidentally

**Comment by kumavis** [comment]
@jbenet here `tree` is just returning the remote links, not attempting to resolve them

**Comment by kumavis** [comment]
@diasdavid does the CID generation look good? see https://github.com/ipld/js-ipld-eth-block/commit/cbc48aa0e63c2843c7a9bb429ceab9b715f91bea
`rawhash` is a buffer. also, this code will error as-is until we have `keccak-256` support.
tracking proper CID here https://github.com/ipld/js-ipld-eth-block/issues/3

**Pull request merged**
